name: Action Unit Test

on: [push, pull_request]

jobs:
  unit-test:
    strategy:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: "treebeardtech/nbmake-action@v0.2"
        with:
          path: "./examples"
          path-output: .
          notebooks: |
            nb1.ipynb
            'sub dir/*.ipynb'
